name: Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run Black formatter check
      run: |
        black --check --diff app/
    
    - name: Run Flake8 linting
      run: |
        flake8 app/ --max-line-length=88 --extend-ignore=E203,W503 --statistics
    
    - name: Run MyPy type checking
      run: |
        mypy app/ --ignore-missing-imports
    
    - name: Run Pylint
      run: |
        pylint app/ --rcfile=.pylintrc || true
    
    - name: Calculate complexity
      run: |
        python -m pip install radon
        radon cc app/ -a -nb
        radon mi app/ -nb
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}